//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentApi
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> grade { get; set; }
        public string Address { get; set; }
        public Nullable<int> Pin { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<int> CourseID { get; set; }
    }
}
