<?xml version="1.0" encoding="utf-8"?><Database Name="EmployeeLinq" Class="DataLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=NAG1-LHP_N76275;Initial Catalog=EmployeeLinq;Integrated Security=True" SettingsObjectName="DataAccessLayerEmp.Properties.Settings" SettingsPropertyName="EmployeeLinqConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="Id" Type="System.String" DbType="NVarChar(10)" IsPrimaryKey="true" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="Salary" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Dept_Id" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="" Member="Class1s">
    <Type Name="Class1" />
  </Table>
</Database>